apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: incident-api
  namespace: incident-lab
  labels:
    app.kubernetes.io/part-of: devops-incident-lab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: incident-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
