apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: incident-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: incident-lab-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
      - op: replace
        path: /data/CHAOS_ENABLED
        value: "false"
images:
  - name: incident-lab-image
    newName: ghcr.io/grvtech1/devops-incident-lab
    digest: sha256:fb7eb08eafbe05ea31f428deb73aaf9aa71653f12833cf0c80bef5f00e709a58
