apiVersion: v1
kind: Service
metadata:
  name: incident-api
  namespace: incident-lab
  labels:
    app.kubernetes.io/name: incident-api
    app.kubernetes.io/part-of: devops-incident-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: incident-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
